### ISSUE TITLE
Downloading script error

### ISSUE THREAD

**Issue by antonzub99** [GAP-LAB-CUHK-SZ/MVHumanNet#10]
Thank you for releasing the downloading script!

When running the command with `${LINK_TO_SAMPLES}` being one of the downloading links I got after submitting the form

```
python download_tool_mvhuman.py --data_name MVHumanNet_0_samples --url ${LINK_TO_SAMPLES} --download_folder ./test_mvhuman_data
```
It fails with the following error:
```
Traceback (most recent call last):
  File "download_tool_mvhuman.py", line 270, in <module>
    getFiles(args.url, download_folder , force )
  File "download_tool_mvhuman.py", line 203, in getFiles
    if "NextHref" in graphqlReq["data"]["legacy"]["renderListDataAsStream"]["ListData"]:
TypeError: 'NoneType' object is not subscriptable
```

And if we take a look at what exactly ` graphqlReq` contains, it has only:
```
{
    "data": {
        "legacy": {
            "renderListDataAsStream": null
        },
        "perf": {
            "executionTime": 13.4078,
            "overheadTime": 7.7014000000000005,
            "parsingTime": 0.0546,
            "queryCount": 3,
            "validationTime": 0.6479,
            "resolvers": [
                {
                    "name": "Mondo",
                    "queryCount": 2,
                    "resolveTime": 10.076500000000001,
                    "waitTime": 0.7769
                },
                {
                    "name": "RenderListDataAsStream",
                    "queryCount": 1,
                    "resolveTime": 2.803099999999999,
                    "waitTime": 11.164900000000001
                }
            ]
        }
    },
    "errors": [
        {
            "message": "Item not found",
            "extensions": {
                "code": "itemNotFound"
            }
        },
        {
            "message": "Item not found",
            "locations": [
                {
                    "line": 8,
                    "column": 7
                }
            ],
            "path": [
                "legacy",
                "renderListDataAsStream"
            ],
            "extensions": {
                "code": "itemNotFound"
            }
        }
    ]
}
```

I assume GraphQL query fails to retrieve links to the contents in the folder with the data.

**Comment by antonzub99** [comment]
It appears to have been fixed, now the script works as intended! Closing the issue.

**Comment by harlanhong** [comment]
Hi, I also met the same problem. Could you share the solution?

**Comment by wenkaier** [comment]
rerun
